Dockerfile, examples/hello/bin/main.dart, examples/hello/lib/app.dart, examples/hello/test/ensure_build_test.dart, examples/hello/test/function_test.dart, functions_framework/lib/functions_framework.dart, functions_framework/lib/serve.dart, functions_framework/lib/src/function_config.dart, functions_framework_builder/lib/builder.dart
=> Add copyright to sources

examples/hello/bin/main.dart, functions_framework_builder/lib/builder.dart
=> Add preamble for generated file

Dockerfile
=> Force rebuild out-of-date generated files when there are conflicts

Dockerfile
=> Refactor dockerfile: don't need to activate mono_repo

test/hello/lib/app.dart, test/hello/test/function_test.dart
Allows for nice debugging when deployed
=> Add and test special handlers to test/hello

functions_framework/CHANGELOG.md, functions_framework/lib/src/cloud_metadata.dart, functions_framework/lib/src/constants.dart, functions_framework/lib/src/logging.dart, functions_framework/lib/src/run.dart, functions_framework/pubspec.yaml, test/hello/test/function_test.dart
Fixes https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/35
=> Detect if running on Google Cloud and log appropriately 

functions_framework/lib/serve.dart, functions_framework/lib/src/logging.dart, functions_framework/lib/src/run.dart, test/hello/lib/app.dart, test/hello/test/cloud_behavior_test.dart, test/hello/test/function_test.dart
Towards https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/41
Refactored run to be more simple and allow for unit testing
Added tests to validate print output when hosted on Google Cloud
=> Use zones to capture print calls within a call and log them correctly

.github/workflows/lint.yml, .github/workflows/unit.yml, tool/ci.sh
Run with the latest 3.2 -> 3.4
Improves the usability within GitHub, better names, etc
=> Use latest mono_repo

README.md
Excludes other branches, PRs, etc
=> Status table: show only for main branch

test/hello/lib/app.dart
Useful for understanding and debugging operation state when hosted
=> test/hello: Add more info for the /info handler

examples/hello/README.md, examples/hello/bin/server.dart, examples/hello/lib/functions.dart
Just a bit more detail for the HTTP example related to changes in v0.2.0.
=> Adding more detail to examples/hello

.github/workflows/conformance.yml, CONTRIBUTING.md, functions_framework/CHANGELOG.md, functions_framework/lib/functions_framework.dart, functions_framework/lib/serve.dart, functions_framework/lib/src/cloud_event_wrapper.dart, functions_framework/lib/src/function_config.dart, functions_framework/lib/src/function_endpoint.dart, functions_framework/pubspec.yaml, functions_framework_builder/lib/builder.dart, functions_framework_builder/lib/src/supported_function_types.dart, functions_framework_builder/test/builder_test.dart, test/hello/bin/server.dart, test/hello/test/cli_test.dart
Towards https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/1
Related to https://github.com/GoogleCloudPlatform/functions-framework-conformance/issues/58
=> Terminate if the configured signature doesn't match the function

functions_framework/CHANGELOG.md, functions_framework/lib/functions_framework.dart, functions_framework_builder/CHANGELOG.md, functions_framework_builder/pubspec.yaml
Sync up the builder version with functions_framework
=> Update the changelog for functions_framework

functions_framework/lib/src/cloud_event.dart, functions_framework/lib/src/cloud_event.g.dart, functions_framework/lib/src/cloud_event_wrapper.dart, test/hello/test/cloud_event_test.dart
Required values are checked
Proper errors are produced
=> Basic validation of CloudEvent requests

Dockerfile, examples/hello/Dockerfile
=> Explicit tag for google/dart image

functions_framework/lib/serve.dart, functions_framework/lib/src/bad_request_exception.dart, functions_framework/lib/src/cloud_event_wrapper.dart, functions_framework/lib/src/log_severity.dart, functions_framework/lib/src/logging.dart, test/hello/test/cloud_behavior_test.dart, test/hello/test/cloud_event_test.dart, test/hello/test/function_test.dart
Correctly handle, reply to, and log bad requests
Fixes https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/1
=> Finish Cloud Event work

functions_framework/CHANGELOG.md, functions_framework/lib/functions_framework.dart, functions_framework/lib/src/log_severity.dart, functions_framework/lib/src/logging.dart, functions_framework_builder/lib/src/supported_function_types.dart, test/hello/bin/server.dart, test/hello/lib/functions.dart, test/hello/test/cli_test.dart, test/hello/test/cloud_behavior_test.dart, test/hello/test/logging_test.dart
- Unify logging logic
- Add TODO around validating FUNCTION_TARGET
- cli_test: whitespace cleanup
- Add `logger` top-level member to access logging interface
=> 4 commits, including adding structured logging

functions_framework_builder/lib/src/supported_function_types.dart, functions_framework_builder/lib/src/utils.dart, functions_framework_builder/test/builder_test.dart, functions_framework_builder/test/test_examples/complex_target_name_handlers.dart
Fixes https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/83
=> Escape `targetName` correctly in (hopefully) all cases

docs/release_process.md
Fixes https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/82
=> Initial documentation of release process

functions_framework/CHANGELOG.md, functions_framework/lib/functions_framework.dart, functions_framework/lib/src/bad_request_exception.dart, functions_framework/lib/src/logging.dart, test/hello/lib/functions.dart, test/hello/test/cloud_event_test.dart, test/hello/test/function_test.dart
Fixes https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/88
=> Expose BadRequestException for use in handlers

CONTRIBUTING.md, README.md, examples/hello/README.md, functions_framework/README.md
Used auto-fix features in VS Code
Standardized and fixed shell code blocks
=> General markdown file cleanup

functions_framework/lib/src/cloud_event_wrapper.dart, functions_framework/lib/src/json_request_utils.dart, test/hello/test/cloud_behavior_test.dart
Towards https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/100
=> Move JSON utils into their own library

functions_framework/lib/src/function_endpoint.dart
=> functions_framework: make implementation classes private

examples/raw_cloudevent/README.md
One correction and minor edits for clarity.
=> Update cloudevent readme

.github/workflows/markdown_linter.yml, .markdownlint.yaml, README.md, docs/01-introduction.md, docs/release_process.md, functions_framework/CHANGELOG.md, functions_framework/README.md, functions_framework_builder/CHANGELOG.md, functions_framework_builder/README.md, tool/markdown_linter_config.yaml
Feel free to close PR to reject proposal.
=> Proposed lint rule change and fix for readme line length

functions_framework_builder/lib/builder.dart, functions_framework_builder/lib/src/function_type_validator.dart, functions_framework_builder/lib/src/generic_function_type.dart, functions_framework_builder/lib/src/supported_function_type.dart, test/hello/lib/functions.dart, test/hello/lib/src/conformance_handlers.dart, test/hello/lib/src/json_handlers.dart, test/hello/lib/src/utils.dart
Update test/hello to fully exercise this pattern
=> Fix issue with functions being exported in target lib/functions.dart

examples/hello/pubspec.yaml, examples/json/pubspec.yaml, examples/raw_cloudevent/pubspec.yaml
=> Remove build_verify dev_dependency from examples

functions_framework/CHANGELOG.md, functions_framework/lib/src/request_context.dart, functions_framework/lib/src/targets/cloud_event_targets.dart, functions_framework/lib/src/targets/json_targets.dart, test/hello/lib/functions.dart, test/hello/lib/src/json_handlers.dart, test/hello/test/cloud_event_test.dart, test/hello/test/custom_type_test.dart, test/hello/test/src/test_utils.dart
fixes https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/108
=> Add responseHeaders to RequestContext

functions_framework_tool/CHANGELOG.md, functions_framework_tool/README.md
=> Add README and CHANGELOG for functions_framework_tool package

examples/raw_cloudevent/pubspec.yaml
This slipped by us yesterday...
=> Update cloudevent example pubspec

functions_framework/CHANGELOG.md, functions_framework/lib/src/request_context.dart, functions_framework/pubspec.yaml
Deprecated headers and headersAll
Fixes https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/127
=> RequestContext - add request property

functions_framework/CHANGELOG.md, functions_framework/pubspec.yaml, functions_framework_builder/pubspec.yaml
Bump to 0.3.2 to publish windows sigterm fix.
=> Prepare to release v0.3.1 of pkg:functions_framework

examples/raw_cloudevent/Dockerfile, examples/raw_cloudevent/README.md
Add missing command flag to Dockerfile
Fix spelling mistake
=> Fix raw_cloudevent example

test/hello/test/cloud_event_test.dart
Setting up for adding specific support for pubsub
=> Update pubsub test to match ~exactly what we get over the wire

functions_framework/lib/src/function_config.dart, functions_framework/lib/src/json_request_utils.dart
Inspired by experiments with null-safety migration
=> Tiny cleanup

functions_framework/CHANGELOG.md, functions_framework/lib/serve.dart, functions_framework/lib/src/function_target.dart, functions_framework/lib/src/request_context.dart, functions_framework/lib/src/targets/cloud_event_targets.dart, functions_framework/lib/src/targets/http_targets.dart, functions_framework/lib/src/targets/json_targets.dart, functions_framework/pubspec.yaml, functions_framework_builder/CHANGELOG.md, functions_framework_builder/lib/builder.dart, functions_framework_builder/lib/src/generic_function_type.dart, functions_framework_builder/lib/src/supported_function_type.dart, functions_framework_builder/pubspec.yaml, functions_framework_builder/test/builder_test.dart, test/hello/bin/server.dart, test/hello/test/cloud_behavior_test.dart
See the changelog for all of the details
tl;dr: enables future flexibility because we no longer require
const constructors
=> Breaking changes to functions_framework

examples/fullstack/backend/pubspec.yaml, examples/fullstack/frontend/build.yaml, examples/fullstack/frontend/lib/main.dart, examples/fullstack/frontend/lib/services/api_types.g.dart, examples/fullstack/frontend/pubspec.yaml, examples/fullstack/frontend/test/widget_test.dart
Cleaned-up bits in the pubspecs
Fixed some lints
Add an ignore to the generated code
=> Cleanup for the fullstack demo

examples/fullstack/backend/bin/server.dart, examples/fullstack/backend/lib/functions.dart
Enhance backend example with request.context.logger.
=> Add request context logger to full stack demo

examples/fullstack/backend/lib/functions.dart
Avoid functions starting with `get`
https://dart.dev/guides/language/effective-dart/design#avoid-starting-a-method-name-with-get
Make members private if they can be private
Use default constructor for Random – it already makes sure it's seeded based on current time, etc
use a const list for salutations
=> fullstack: A bit more cleanup to the server function

examples/fullstack/README.md, examples/fullstack/backend/README.md, examples/fullstack/frontend-cli/.gitignore, examples/fullstack/frontend-cli/README.md, examples/fullstack/frontend-cli/analysis_options.yaml, examples/fullstack/frontend-cli/bin/greet.dart, examples/fullstack/frontend-cli/lib/api_types.dart, examples/fullstack/frontend-cli/lib/api_types.g.dart, examples/fullstack/frontend-cli/pubspec.yaml, examples/fullstack/frontend/README.md
Simple command-line example (`frontend-cli`) to augment the Flutter app (`frontend`) for connecting to the `backend`.
=> Fullstack demo (simple command-line example)

functions_framework/pubspec.yaml, functions_framework_builder/CHANGELOG.md, functions_framework_builder/pubspec.yaml, test/hello/pubspec.yaml
Prepare to release builder v0.4.1
=> Bump latest deps on function_framework[_builder]

functions_framework_builder/lib/src/valid_json_utils.dart, functions_framework_builder/test/builder_test.dart, functions_framework_builder/test/test_examples/freezed_style_json_mixin_handler.dart
- updated _validJsonReturnTypeCore to also check a type's mixins for valid toJson methods
fixes #216
=> Update builder to check mixins for toJson

functions_framework_builder/CHANGELOG.md, functions_framework_builder/pubspec.yaml
=> builder: changelog entry for previous PR, update functions_framework dep

dartfn/pubspec.lock, examples/fullstack/backend/pubspec.lock, examples/fullstack/frontend-cli/pubspec.lock, examples/fullstack/frontend/pubspec.lock, examples/hello/pubspec.lock, examples/json/pubspec.lock, examples/raw_cloudevent/pubspec.lock, test/hello/pubspec.lock, tool/pub_upgrade.dart
Include a tool to make this easy
=> Update checked-in pubspec.lock files

dartfn/pubspec.lock, functions_framework/lib/src/logging.dart, test/hello/pubspec.lock
Also updated pinned dependencies
=> Tiny tweak to logging doc comment

dartfn/pubspec.lock, examples/fullstack/backend/pubspec.lock, examples/fullstack/frontend-cli/pubspec.lock, examples/hello/pubspec.lock, examples/json/pubspec.lock, examples/raw_cloudevent/pubspec.lock, functions_framework/lib/src/cloud_event.g.dart, functions_framework/pubspec.yaml, functions_framework_builder/CHANGELOG.md, functions_framework_builder/pubspec.yaml, test/hello/lib/src/pub_sub_types.g.dart, test/hello/pubspec.lock, test/hello/pubspec.yaml
Bump lock files across the board
Update generated code
=> builder: support the latest pkg:analyzer, prepare for release

functions_framework_builder/CHANGELOG.md, functions_framework_builder/lib/builder.dart, functions_framework_builder/pubspec.yaml
=> builder: sort directives in generated bin/server.dart

examples/fullstack/frontend/build.yaml, examples/fullstack/frontend/lib/services/api_types.g.dart, examples/fullstack/frontend/pubspec.lock, examples/fullstack/frontend/pubspec.yaml
=> fix: update examples/fullstack/frontend deps

.github/workflows/lint.yml, .github/workflows/unit.yml, examples/fullstack/frontend/lib/views/home_page.dart, integration_test/lib/functions.dart, integration_test/mono_pkg.yaml, integration_test/pubspec.yaml
- refactor: Remove unneeded import
- ci: Verify frontend-cli example in CI
- refactor: integration_test: drop usage of pkg:pedantic
=> refactor: unneeded imports and drop dependency

.github/workflows/lint.yml, .github/workflows/unit.yml, dartfn/mono_pkg.yaml, functions_framework/mono_pkg.yaml, functions_framework_builder/mono_pkg.yaml, integration_test/mono_pkg.yaml, tool/ci.sh
Updated project `mono_pkg.yaml` configs for latest [mono_repo 6.0.0](https://pub.dev/packages/mono_repo/versions/6.0.0)
=> chore: Updated for mono_repo 6.0.0

.github/workflows/lint.yml, .github/workflows/unit.yml, tool/ci.sh
=> Latest mono_repo

.github/workflows/lint.yml, .github/workflows/unit.yml, .github/workflows/verify_examples.yml, functions_framework_builder/CHANGELOG.md, functions_framework_builder/lib/src/generic_function_type.dart, functions_framework_builder/lib/src/valid_json_utils.dart, functions_framework_builder/pubspec.yaml, integration_test/pubspec.yaml, tool/ci.sh
Closes https://github.com/GoogleCloudPlatform/functions-framework-dart/pull/352
Closes https://github.com/GoogleCloudPlatform/functions-framework-dart/pull/353
=> chore: latest mono_repo

.github/dependabot.yml, .github/workflows/conformance.yml
=> chore: blast_repo fixes

.github/workflows/publish.yaml
=> blast_repo fixes

docs/quickstarts/03-quickstart-cloudrun.md
Turns out this doesn't require any mention of `beta`
=> Cloud Run Quickstart - Take 2

functions_framework/CHANGELOG.md, functions_framework/lib/src/json_request_utils.dart, functions_framework/lib/src/targets/cloud_event_targets.dart, functions_framework/lib/src/targets/json_targets.dart, functions_framework/pubspec.yaml, integration_test/test/custom_type_test.dart
Closes https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/391
Also improve efficiency of JSON decoding
=> feature: support protobuf cloud events

functions_framework/lib/src/json_request_utils.dart, functions_framework/lib/src/targets/cloud_event_targets.dart, functions_framework/lib/src/targets/json_targets.dart
=> chore: correctly consider encoding when decoding JSON from request

functions_framework/lib/src/json_request_utils.dart, functions_framework/lib/src/targets/cloud_event_targets.dart, integration_test/bin/server.dart, integration_test/lib/functions.dart, integration_test/test/cloud_event_test.dart
Encode data as Uint8List when possible
Add tests
=> Core: refactoring protobuf support

examples/protobuf_firestore/pubspec.yaml, examples/protobuf_firestore/test/decode_test.dart
=> chore: drop dependency override in example

functions_framework_builder/lib/src/analyzer_utils.dart
- **chore: DRY up utils in builder**
- **Work around recent change in pkg:analyzer**
=> i464 function shape silly
