GoogleCloudPlatform/functions-framework-dart

Dockerfile
Dockerfile no longer builds to an output directory, so this PR cleans up the build command.
=> Remove build options, no longer needed

functions_framework/lib/src/function_config.dart
DRY up ArgParser keys
Trailing commas in functions that wrap
=> Small cleanup to FunctionConfig

functions_framework_builder/lib/builder.dart, functions_framework_builder/lib/src/utils.dart, functions_framework_builder/pubspec.yaml, functions_framework_builder/test/builder_test.dart, functions_framework_builder/test/test_examples/all_valid_shapes.dart
- Validate that adding a `target` to @CloudFunction parses
- Make sure only one function has a given `target`
- Test that all valid function shapes are supported
- Validate that annotated members are functions with the right parameters and return type.
=> Add a number of checks to the builder

functions_framework/lib/src/logging.dart, test/hello/lib/app.dart, test/hello/pubspec.yaml, test/hello/test/cloud_behavior_test.dart, test/hello/test/function_test.dart
Use zones for all error handling
Make sure errors thrown outside a normal async call are also handled and logged
Fixes https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/41
=> Finish work to handle errors in a Zone and log them correctly

examples/hello/Dockerfile
This adds `--delete-conflicting-output` to DockerFile when running `build_runner`
Closes https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/54
=> Update DockerFile in hello example

functions_framework/CHANGELOG.md, functions_framework/lib/functions_framework.dart, functions_framework/pubspec.yaml, functions_framework_builder/lib/builder.dart, functions_framework_builder/test/builder_test.dart, functions_framework_builder/test/test_examples/all_valid_shapes.dart, test/hello/bin/server.dart, test/hello/lib/functions.dart, test/hello/pubspec.yaml, test/hello/test/cloud_behavior_test.dart
If `target` is not provided, the name of the function is now used
Now properly reject private functions
Now reject functions annotated twice
=> Update `CloudFunction` so target is now an option-named parameter

functions_framework/lib/src/cloud_event_wrapper.dart, functions_framework/lib/src/function_config.dart, test/hello/bin/server.dart, test/hello/lib/functions.dart, test/hello/test/function_test.dart
- Rename (internal) enum FunctionType.cloudevent (from cloudEvent)
- Add unit test for binary messages
- Support structured event types
=> 3 separate commits - will land individually

test/hello/test/cli_test.dart, test/hello/test/cloud_event_test.dart, test/hello/test/function_test.dart, test/hello/test/src/test_utils.dart
Move common utilities to shared library
Make it easy to run tests with a random listening port
This makes sure we don't have two tests running in parallel that
collide on 8080
=> test/hello: split tests into multiple, focused files

functions_framework/lib/src/log_severity.dart, functions_framework/lib/src/logging.dart, test/hello/test/cloud_behavior_test.dart
- make a cloud event handler THE handler
- Log bad request details at the same level as a 400 response: warning
=> i80 bad request log level

docs/quick-starts/03-quick-start-cloud-run.md
Without blank line, breaks bold for `**Congratulations!**`.
=> Need a blank line after br tag

LICENSE, README.md, functions_framework_builder/LICENSE
Fixes #107
Restoring original Apache licenses across mono repo for consistency.
=> Fix license

docs/quick-starts/03-quick-start-cloud-run.md
Minor edit: should be `run/region` for Cloud Run, not `compute/region`
=> Fix quick start for Cloud Run

docs/quickstarts/02-quickstart-docker.md
Don't know how the following slipped through CI, but fixed now.
```
$ markdownlint-cli2 "**/*.md"
markdownlint-cli2 v0.0.13 (markdownlint v0.22.0)
Finding: **/*.md
Linting: 15 file(s)
Summary: 1 error(s)
docs/quickstarts/02-quickstart-docker.md:163:76 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
```
=> Remove trailing whitespace

examples/json/pubspec.yaml, examples/raw_cloudevent/pubspec.yaml, functions_framework_builder/CHANGELOG.md, functions_framework_builder/pubspec.yaml
Also dropped dev_dependecy on function_framework in two examples
=> Prepare to release v0.3.0 of functions_framework_builder

functions_framework_tool/CHANGELOG.md, functions_framework_tool/README.md, functions_framework_tool/bin/dartfn.dart, functions_framework_tool/build.yaml, functions_framework_tool/lib/src/version.dart, functions_framework_tool/pubspec.yaml
So that users can just run:
```shell
dart pub global activate dartfn
```
instead of
```shell
dart pub global activate functions_framework_tool
```
=> Rename tool pub name to dartfn

functions_framework/lib/serve.dart
(Maybe) Fixes #151 
Registering a SIGTERM handler on Windows raises an exception.
@kevmoo PTAL. Things to consider: this explicitly checks for Windows, but it might be better to just try to catch the exception and then log that the SIGTERM handler couldn't be registered for the host OS.
Before merging this, we should get someone with Windows expertise to weigh in. I left [this comment](https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/151#issuecomment-751812565) in the issue, copied here for convenience:
> While the exception would seem to indicate that SIGTERM isn't supported, I found this [old Microsoft doc](https://docs.microsoft.com/en-us/previous-versions/ms811896(v=msdn.10)?redirectedfrom=MSDN#ucmgch09_topic3) that seems to indicate that SIGTERM *is* supported. …
=> Don't register SIGTERM handler on Windows

functions_framework/CHANGELOG.md
I've updated the changelog for `functions_framework`. However, I think we should get this published so Windows devs aren't blocked. I can either bump `0.3.1-dev` in the changelog and pubspec to `0.3.1` with this PR or with a following PR so we can publish the fix.
=> Add fix for sigterm error on windows to changelog

examples/fullstack/README.md, examples/fullstack/frontend/README.md
Adds requirements for the fullstack demo.
I wasn't able to run the application without these requirements (probably already setup for y'all).
=> docs: add requirements to fullstack example readme

functions_framework/CHANGELOG.md, functions_framework/README.md, functions_framework/example/readme.md, functions_framework/lib/functions_framework.dart, functions_framework/lib/serve.dart, functions_framework/lib/src/cloud_event.dart, functions_framework/lib/src/log_severity.dart, functions_framework/lib/src/request_context.dart, functions_framework/lib/src/typedefs.dart, functions_framework/pubspec.yaml
Should increase the score of the package
Prepare to release v0.4.1
=> Add documentation to many public members and populate the example dir

functions_framework/CHANGELOG.md, functions_framework/lib/serve.dart
Correct the doc comment on the `serve` function
=> Centralize printing error info and setting the exit code

docs/quickstarts/03-quickstart-cloudrun.md
`gcloud run deploy --source` is now GA, quickstarts are supposed to be opinionated and use the fastest way to get started. 
I suggest to delete the alternative option of build + deploy in two commands.
=> Simplify quickstart by only using `gcloud run deploy --source`

functions_framework/lib/src/request_context.dart, functions_framework/lib/src/targets/http_targets.dart, gcp/lib/gcp.dart, gcp/lib/src/logging.dart, integration_test/lib/functions.dart
The previous model would have dropped the logger with calls to
Request.change because it was based on Expando
=> fix: tie logging to the Zone, not the request

docs/quickstarts/03-quickstart-cloudrun.md
Adds Cloud SQL-specific documentation about passing `--execution-environment=gen2`, which is required to avoid the bug outlined in #302.
As of this writing, the `--execution-environment` parameter is only available in the gcloud CLI beta. Once that lands in the stable CLI, we could collapse this additional section back into the original invocation.
=> Documentation for connecting to Cloud SQL

.github/dependabot.yml, .github/workflows/conformance.yml, .github/workflows/no-response.yml, .github/workflows/publish.yaml
This PR contains changes created by the blast repo tool.
- `auto-publish`
- `dependabot`
- `github-actions`
- `no-response`
=> blast repo changes: auto-publish, dependabot, github-actions, no-response

gcp/CHANGELOG.md, gcp/lib/src/logging.dart, gcp/pubspec.yaml
Closes #394 
Currently, log messages do not get interpreted as jsonPayload even if a JSON object is provided:
```dart
log({'hello': 'world'});
```
results in:
```
textPayload: "{hello: world}"
```
This change results in the following log:
```
jsonPayload: {
message: {
hello: world
}
}
```
Are there existing tests for the logger? I looked but wasn't able to find any.
=> fix(gcp): allow logging message as jsonPayload
